#[cfg(test)]
mod tests {
    use jieba_rs::Jieba;

    #[test]
    fn test_jieba_cut() {
        let jieba = Jieba::new();
        let text = "The quick (\"brown\") fox can't jump 32.3 feet, right? 我将点燃星海！天上的stars全部都是 eye，不要凝视";
        let words = jieba.cut(text, false);
        let vec = vec![
            "The",
            " ",
            "quick",
            " ",
            "(",
            "\"",
            "brown",
            "\"",
            ")",
            " ",
            "fox",
            " ",
            "can",
            "'",
            "t",
            " ",
            "jump",
            " ",
            "32",
            ".",
            "3",
            " ",
            "feet",
            ",",
            " ",
            "right",
            "?",
            " ",
            "我",
            "将",
            "点燃",
            "星海",
            "！",
            "天上",
            "的",
            "stars",
            "全部都是",
            " ",
            "eye",
            "，",
            "不要",
            "凝视",
        ];
        assert_eq!(words, vec);
        let words = jieba.cut(text, true);
        let vec = vec![
            "The",
            " ",
            "quick",
            " ",
            "(",
            "\"",
            "brown",
            "\"",
            ")",
            " ",
            "fox",
            " ",
            "can",
            "'",
            "t",
            " ",
            "jump",
            " ",
            "32.3",
            " ",
            "feet",
            ",",
            " ",
            "right",
            "?",
            " ",
            "我",
            "将",
            "点燃",
            "星海",
            "！",
            "天上",
            "的",
            "stars",
            "全部都是",
            " ",
            "eye",
            "，",
            "不要",
            "凝视",
        ];
        assert_eq!(words, vec);
    }
}
